name: go-light-framework

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    profiles: ["dev", "prod"]
    restart: always
    ports:
      - "127.0.0.1:${SERVER_PORT}:8080"
    secrets:
      - env
      - jws_private_key
      - client_secret_2_557898105577
    environment:
      - ENV_FILE_PATH=/run/secrets/env
    networks:
      - app-network
    depends_on:
      psql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  psql:
    build: ./docker/postgres
    profiles: ["dev-watch", "dev", "prod"]
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build: ./docker/redis
    profiles: ["dev-watch", "dev", "prod"]
    restart: always
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-dev-air:
    build:
      context: .
      dockerfile: ./docker/watch_app/Dockerfile
    profiles: ["dev-watch"]
    restart: always
    ports:
      - "127.0.0.1:${SERVER_PORT}:8080"
    volumes:
      - ./:/app
    secrets:
      - env
      - jws_private_key
      - client_secret_2_557898105577
    environment:
      - ENV_FILE_PATH=/run/secrets/env
    networks:
      - app-network
    depends_on:
      psql:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgadmin:
    build: ./docker/pgadmin
    profiles: ["dev-watch", "dev"]
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "127.0.0.1:7894:80"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - psql

  redisinsight:
    build: ./docker/redisinsight
    profiles: ["dev-watch", "dev"]
    restart: always
    ports:
      - "127.0.0.1:5540:5540"
    volumes:
      - redisinsight_volume:/data
    networks:
      - app-network
    depends_on:
      - redis

volumes:
  psql_volume:
  redis_volume:
  pgadmin_volume:
  redisinsight_volume:

networks:
  app-network:
    driver: bridge

secrets:
  env:
    file: .env
  jws_private_key:
    file: jws_private_key.pem
  client_secret_2_557898105577:
    file: client_secret_2.json
