// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package database_queries

import (
	"context"
)

// iteratorForMfaInsertBackupCodes implements pgx.CopyFromSource.
type iteratorForMfaInsertBackupCodes struct {
	rows                 []MfaInsertBackupCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForMfaInsertBackupCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForMfaInsertBackupCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].CodeHash,
	}, nil
}

func (r iteratorForMfaInsertBackupCodes) Err() error {
	return nil
}

// MfaInsertBackupCodes
//
//	INSERT INTO
//	  backup_codes (user_id, code_hash)
//	VALUES
//	  ($1::INT, $2::TEXT)
func (q *Queries) MfaInsertBackupCodes(ctx context.Context, arg []MfaInsertBackupCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"backup_codes"}, []string{"user_id", "code_hash"}, &iteratorForMfaInsertBackupCodes{rows: arg})
}

// iteratorForPermAddPermissionsToRoles implements pgx.CopyFromSource.
type iteratorForPermAddPermissionsToRoles struct {
	rows                 []PermAddPermissionsToRolesParams
	skippedFirstNextCall bool
}

func (r *iteratorForPermAddPermissionsToRoles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermAddPermissionsToRoles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RoleName,
		r.rows[0].PermissionName,
	}, nil
}

func (r iteratorForPermAddPermissionsToRoles) Err() error {
	return nil
}

// PermAddPermissionsToRoles
//
//	INSERT INTO
//	  role_permission (role_name, permission_name)
//	VALUES
//	  ($1, $2)
func (q *Queries) PermAddPermissionsToRoles(ctx context.Context, arg []PermAddPermissionsToRolesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"role_permission"}, []string{"role_name", "permission_name"}, &iteratorForPermAddPermissionsToRoles{rows: arg})
}

// iteratorForPermCreateNewPermissions implements pgx.CopyFromSource.
type iteratorForPermCreateNewPermissions struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForPermCreateNewPermissions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermCreateNewPermissions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForPermCreateNewPermissions) Err() error {
	return nil
}

// PermCreateNewPermissions
//
//	INSERT INTO
//	  permission (name)
//	VALUES
//	  ($1)
func (q *Queries) PermCreateNewPermissions(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"permission"}, []string{"name"}, &iteratorForPermCreateNewPermissions{rows: name})
}

// iteratorForPermCreateNewRoles implements pgx.CopyFromSource.
type iteratorForPermCreateNewRoles struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForPermCreateNewRoles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPermCreateNewRoles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForPermCreateNewRoles) Err() error {
	return nil
}

// PermCreateNewRoles
//
//	INSERT INTO
//	  role (name)
//	VALUES
//	  ($1)
func (q *Queries) PermCreateNewRoles(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"role"}, []string{"name"}, &iteratorForPermCreateNewRoles{rows: name})
}

// iteratorForSessionStoreStoreAttrs implements pgx.CopyFromSource.
type iteratorForSessionStoreStoreAttrs struct {
	rows                 []SessionStoreStoreAttrsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSessionStoreStoreAttrs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSessionStoreStoreAttrs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Session,
		r.rows[0].AttrKey,
		r.rows[0].AttrValue,
		r.rows[0].ExpiresAt,
	}, nil
}

func (r iteratorForSessionStoreStoreAttrs) Err() error {
	return nil
}

// SessionStoreStoreAttrs
//
//	INSERT INTO
//	  session_store (session, attr_key, attr_value, expires_at)
//	VALUES
//	  (
//	    $1::TEXT,
//	    $2::TEXT,
//	    $3::TEXT,
//	    $4::timestamptz
//	  )
func (q *Queries) SessionStoreStoreAttrs(ctx context.Context, arg []SessionStoreStoreAttrsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"session_store"}, []string{"session", "attr_key", "attr_value", "expires_at"}, &iteratorForSessionStoreStoreAttrs{rows: arg})
}
