// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa.sql

package database_queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const mfaCreateTypeEmail = `-- name: MfaCreateTypeEmail :one
WITH new_mfa_method AS(
    INSERT INTO mfa_method (
        status,
        method_type,
        user_id,
        label
        )
    VALUES (
        'pending',
        'email',
        $3::int,
        $4::text
    )
    RETURNING id
)
INSERT INTO mfa_method_type_email (
    id,
    ownership_verification,
    email
    )
VALUES (
    (SELECT id from new_mfa_method),
    $1::uuid,
    $2::text
)
RETURNING id
`

type MfaCreateTypeEmailParams struct {
	OwnershipVerification uuid.UUID   `json:"ownership_verification"`
	Email                 string      `json:"email"`
	UserID                int32       `json:"user_id"`
	Label                 pgtype.Text `json:"label"`
}

// MfaCreateTypeEmail
//
//	WITH new_mfa_method AS(
//	    INSERT INTO mfa_method (
//	        status,
//	        method_type,
//	        user_id,
//	        label
//	        )
//	    VALUES (
//	        'pending',
//	        'email',
//	        $3::int,
//	        $4::text
//	    )
//	    RETURNING id
//	)
//	INSERT INTO mfa_method_type_email (
//	    id,
//	    ownership_verification,
//	    email
//	    )
//	VALUES (
//	    (SELECT id from new_mfa_method),
//	    $1::uuid,
//	    $2::text
//	)
//	RETURNING id
func (q *Queries) MfaCreateTypeEmail(ctx context.Context, arg MfaCreateTypeEmailParams) (int32, error) {
	row := q.db.QueryRow(ctx, mfaCreateTypeEmail,
		arg.OwnershipVerification,
		arg.Email,
		arg.UserID,
		arg.Label,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
