// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp_challenge.sql

package database_queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const otpChallengeGet = `-- name: OtpChallengeGet :one
SELECT id, otp_hash, channel, attempts, created_at, updated_at, expires_at
FROM otp_challenge
WHERE id = $1
LIMIT 1
`

// OtpChallengeGet
//
//	SELECT id, otp_hash, channel, attempts, created_at, updated_at, expires_at
//	FROM otp_challenge
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) OtpChallengeGet(ctx context.Context, id uuid.UUID) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, otpChallengeGet, id)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.OtpHash,
		&i.Channel,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const otpChallengeIncAttempt = `-- name: OtpChallengeIncAttempt :one
UPDATE otp_challenge
SET attempts = attempts + $1
WHERE id = $2
  AND attempts <= $3
RETURNING attempts
`

type OtpChallengeIncAttemptParams struct {
	Inc           pgtype.Int4 `json:"inc"`
	ID            uuid.UUID   `json:"id"`
	Attemptslimit pgtype.Int4 `json:"attemptslimit"`
}

// OtpChallengeIncAttempt
//
//	UPDATE otp_challenge
//	SET attempts = attempts + $1
//	WHERE id = $2
//	  AND attempts <= $3
//	RETURNING attempts
func (q *Queries) OtpChallengeIncAttempt(ctx context.Context, arg OtpChallengeIncAttemptParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, otpChallengeIncAttempt, arg.Inc, arg.ID, arg.Attemptslimit)
	var attempts pgtype.Int4
	err := row.Scan(&attempts)
	return attempts, err
}

const otpChallengeInsert = `-- name: OtpChallengeInsert :one
INSERT INTO otp_challenge (
    otp_hash,
    channel,
    attempts,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, otp_hash, channel, attempts, created_at, updated_at, expires_at
`

type OtpChallengeInsertParams struct {
	OtpHash   string             `json:"otp_hash"`
	Channel   string             `json:"channel"`
	Attempts  pgtype.Int4        `json:"attempts"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// OtpChallengeInsert
//
//	INSERT INTO otp_challenge (
//	    otp_hash,
//	    channel,
//	    attempts,
//	    expires_at
//	)
//	VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4
//	)
//	RETURNING id, otp_hash, channel, attempts, created_at, updated_at, expires_at
func (q *Queries) OtpChallengeInsert(ctx context.Context, arg OtpChallengeInsertParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, otpChallengeInsert,
		arg.OtpHash,
		arg.Channel,
		arg.Attempts,
		arg.ExpiresAt,
	)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.OtpHash,
		&i.Channel,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
