// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_store.sql

package database_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionStoreDeleteExpiredRows = `-- name: SessionStoreDeleteExpiredRows :exec
DELETE FROM session_store
WHERE
  expires_at <= NOW()
`

// SessionStoreDeleteExpiredRows
//
//	DELETE FROM session_store
//	WHERE
//	  expires_at <= NOW()
func (q *Queries) SessionStoreDeleteExpiredRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionStoreDeleteExpiredRows)
	return err
}

const sessionStoreGetAttr = `-- name: SessionStoreGetAttr :one
SELECT
  attr_value
FROM
  session_store
WHERE
  session = $1::TEXT
  AND attr_key = $2::TEXT
LIMIT
  1
`

type SessionStoreGetAttrParams struct {
	Session string `json:"session"`
	AttrKey string `json:"attr_key"`
}

// SessionStoreGetAttr
//
//	SELECT
//	  attr_value
//	FROM
//	  session_store
//	WHERE
//	  session = $1::TEXT
//	  AND attr_key = $2::TEXT
//	LIMIT
//	  1
func (q *Queries) SessionStoreGetAttr(ctx context.Context, arg SessionStoreGetAttrParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, sessionStoreGetAttr, arg.Session, arg.AttrKey)
	var attr_value pgtype.Text
	err := row.Scan(&attr_value)
	return attr_value, err
}

const sessionStoreRemoveAttr = `-- name: SessionStoreRemoveAttr :exec
DELETE FROM session_store
WHERE
  session = $1::TEXT
  AND attr_key = $2::TEXT
`

type SessionStoreRemoveAttrParams struct {
	Session string `json:"session"`
	AttrKey string `json:"attr_key"`
}

// SessionStoreRemoveAttr
//
//	DELETE FROM session_store
//	WHERE
//	  session = $1::TEXT
//	  AND attr_key = $2::TEXT
func (q *Queries) SessionStoreRemoveAttr(ctx context.Context, arg SessionStoreRemoveAttrParams) error {
	_, err := q.db.Exec(ctx, sessionStoreRemoveAttr, arg.Session, arg.AttrKey)
	return err
}

const sessionStoreStoreAttr = `-- name: SessionStoreStoreAttr :exec
INSERT INTO
  session_store (session, attr_key, attr_value, expires_at)
VALUES
  (
    $1::TEXT,
    $2::TEXT,
    $3::TEXT,
    $4::timestamptz
  )
`

type SessionStoreStoreAttrParams struct {
	Session   string             `json:"session"`
	AttrKey   string             `json:"attr_key"`
	AttrValue string             `json:"attr_value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// SessionStoreStoreAttr
//
//	INSERT INTO
//	  session_store (session, attr_key, attr_value, expires_at)
//	VALUES
//	  (
//	    $1::TEXT,
//	    $2::TEXT,
//	    $3::TEXT,
//	    $4::timestamptz
//	  )
func (q *Queries) SessionStoreStoreAttr(ctx context.Context, arg SessionStoreStoreAttrParams) error {
	_, err := q.db.Exec(ctx, sessionStoreStoreAttr,
		arg.Session,
		arg.AttrKey,
		arg.AttrValue,
		arg.ExpiresAt,
	)
	return err
}

type SessionStoreStoreAttrsParams struct {
	Session   string             `json:"session"`
	AttrKey   string             `json:"attr_key"`
	AttrValue string             `json:"attr_value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}
