// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package database_queries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreateNewSession = `-- name: SessionCreateNewSession :one
INSERT INTO session (
        token,
        originated_from,
        used_installation,
        expires_at,
        ip_address,
        purpose
    )
VALUES (
    $1::text,
    $2::int,
    $3::int,
    $4::timestamptz,
    $5::INET,
    $6::text
)
RETURNING id
`

type SessionCreateNewSessionParams struct {
	Token            string             `json:"token"`
	OriginatedFrom   int32              `json:"originated_from"`
	UsedInstallation int32              `json:"used_installation"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IpAddress        netip.Addr         `json:"ip_address"`
	Purpose          string             `json:"purpose"`
}

// SessionCreateNewSession
//
//	INSERT INTO session (
//	        token,
//	        originated_from,
//	        used_installation,
//	        expires_at,
//	        ip_address,
//	        purpose
//	    )
//	VALUES (
//	    $1::text,
//	    $2::int,
//	    $3::int,
//	    $4::timestamptz,
//	    $5::INET,
//	    $6::text
//	)
//	RETURNING id
func (q *Queries) SessionCreateNewSession(ctx context.Context, arg SessionCreateNewSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionCreateNewSession,
		arg.Token,
		arg.OriginatedFrom,
		arg.UsedInstallation,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.Purpose,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const sessionDeleteAllActiveSessionsForUser = `-- name: SessionDeleteAllActiveSessionsForUser :exec
DELETE FROM session AS s
USING active_login_identity AS li
WHERE s.originated_from = li.id
AND li.user_id = $1::int
`

// SessionDeleteAllActiveSessionsForUser
//
//	DELETE FROM session AS s
//	USING active_login_identity AS li
//	WHERE s.originated_from = li.id
//	AND li.user_id = $1::int
func (q *Queries) SessionDeleteAllActiveSessionsForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllActiveSessionsForUser, userID)
	return err
}

const sessionDeleteExpiredRows = `-- name: SessionDeleteExpiredRows :exec
DELETE FROM active_session
WHERE expires_at <= NOW()
`

// SessionDeleteExpiredRows
//
//	DELETE FROM active_session
//	WHERE expires_at <= NOW()
func (q *Queries) SessionDeleteExpiredRows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionDeleteExpiredRows)
	return err
}

const sessionDeleteSession = `-- name: SessionDeleteSession :exec
DELETE FROM session
WHERE id = $1
`

// SessionDeleteSession
//
//	DELETE FROM session
//	WHERE id = $1
func (q *Queries) SessionDeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, sessionDeleteSession, id)
	return err
}

const sessionGetActiveSessionById = `-- name: SessionGetActiveSessionById :one
SELECT id, token, ip_address, created_at, updated_at, expires_at, purpose, originated_from, used_installation
FROM active_session
WHERE id = $1
LIMIT 1
`

// SessionGetActiveSessionById
//
//	SELECT id, token, ip_address, created_at, updated_at, expires_at, purpose, originated_from, used_installation
//	FROM active_session
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) SessionGetActiveSessionById(ctx context.Context, id int32) (ActiveSession, error) {
	row := q.db.QueryRow(ctx, sessionGetActiveSessionById, id)
	var i ActiveSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Purpose,
		&i.OriginatedFrom,
		&i.UsedInstallation,
	)
	return i, err
}

const sessionGetActiveSessionByToken = `-- name: SessionGetActiveSessionByToken :one
SELECT id, token, ip_address, created_at, updated_at, expires_at, purpose, originated_from, used_installation
FROM active_session
WHERE token = $1
LIMIT 1
`

// SessionGetActiveSessionByToken
//
//	SELECT id, token, ip_address, created_at, updated_at, expires_at, purpose, originated_from, used_installation
//	FROM active_session
//	WHERE token = $1
//	LIMIT 1
func (q *Queries) SessionGetActiveSessionByToken(ctx context.Context, token string) (ActiveSession, error) {
	row := q.db.QueryRow(ctx, sessionGetActiveSessionByToken, token)
	var i ActiveSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Purpose,
		&i.OriginatedFrom,
		&i.UsedInstallation,
	)
	return i, err
}
